### ISSUE TITLE
Yotta not installed automatically, many gem messages.

### ISSUE THREAD

**Issue by MrYsLab** [carlosperate/microbit-dev-env#6]
Thanks for providing this repo. It certainly makes installing the toolchain a lot simpler than doing everything manually.

I am not sure if this is a bug or not, but I thought you should be aware. After installing, I tried doing a build of DAL V1. The yt commands failed since yotta was not installed. I manually installed yotta into the virtual machine, which solved the problem.

I believe the second issue is probably a vagrant issue, but I am unsure. Upon bringing up vagrant, I get several messages about gem components. If these are benign, no problem. I just wanted to make sure I could safely ignore them. Here is a sample:

```
Ignoring nokogiri-1.10.10 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.10
Ignoring nokogiri-1.10.7 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.7
Ignoring racc-1.5.2 because its extensions are not built. Try: gem pristine racc --version 1.5.2
Ignoring sassc-2.2.1 because its extensions are not built. Try: gem pristine sassc --version 2.2.1
Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7

```

Finally, after bringing up vagrant the first time, I was prompted to upgrade the version of Ubuntu for the VM. I did so, and now the VM is running version 20.04. Again, just checking that this is not going to cause any issues.

**Comment by carlosperate** [comment]
> I am not sure if this is a bug or not, but I thought you should be aware. After installing, I tried doing a build of DAL V1. The yt commands failed since yotta was not installed. I manually installed yotta into the virtual machine, which solved the problem.


When running the `vagrant up` command for the first time, did it ask you what different things you wanted to build?
Like listed in this section? https://github.com/carlosperate/microbit-dev-env#vagrant-project-bring-up

Based on that it will install different tooling. So if you didn't select anything that needed Yotta, it woudn't have installed it.

> I believe the second issue is probably a vagrant issue, but I am unsure

Yeah, I'm not sure what those Vagran errors mean. I have never done any Ruby development, so I don't know if those gem warnings mean much or if they can be safely ignored. In my case I've never seen them before (but it has been a while since the last time I used this project).

> Finally, after bringing up vagrant the first time, I was prompted to upgrade the version of Ubuntu for the VM. I did so, and now the VM is running version 20.04. Again, just checking that this is not going to cause any issues.

Did Vagrant prompt you to updtae the Vagrantfile? Or did the OS upgrade itself?
If everything required was already installed then it's probably okay? But I woudn't be surprised if things break.

Main things I can think of is:
- The arm gcc compiler is installed using a third party apt repository, which might not have deb files for 20.04 (or maybe it does now, but it definitely didn't in the past)
    - If `arm-none-eabi-gcc --version` works fine, then this is probably okay
- In the scripts included here Yotta is installed via pipx, which creates a virtual environment. Upgrading Ubuntu means updating to a newer Python 3.x version, and that has the potential to break Python virtual environments.
    - If you have manually installed it in the system Python installation, then it might be okay, if yotta projects still build then it's probably all fine
    - Yotta does have some problems with Python 3.7 and 3.8, but I do think both cases are macOS specific, so they should be fine inside the Ubuntu VM

**Comment by carlosperate** [comment]
Oh, just to let you know, if things do not quite work it'd be happy to see if they can be easily fixed in this repo, but lately I've been using Docker a lot more than Vagrant, so this might be a bit more guaranteed to work: https://github.com/carlosperate/docker-microbit-toolchain

**Comment by MrYsLab** [comment]
Thanks for the quick reply.

I did select the DAL for v1 and v2 when I started Vagrant for the first time, so it looks like it somehow missed installing yotta. 

Ubuntu upgraded itself and not Vagrant.

I just discovered the docker version of your tool, so I am trying that now. Please feel free to close this issue if you think it is appropriate.

**Comment by carlosperate** [comment]
I'll give this a run later today to see if I can replicate the issue, thanks for the bug report!

**Comment by MrYsLab** [comment]
Great. I just tried the docker version. I prefer to use that—a quick question. I want to try and create a BLE version of [Telemetrix](https://mryslab.github.io/telemetrix/) tailored for the micro:bit v1 and v2 using DAL and CODAL. It looks like the API for the BLE stuff is the arm mbed BLE API.

Is that the correct assumption?

Also, would you know where I can find the API for the more mundane things like setting a pin mode, toggling digital pins, etc. ? 

Thanks.

**Comment by carlosperate** [comment]
Yes, you can find the V1 Mbed BLE API here: https://github.com/lancaster-university/BLE_API

And for V2 in https://github.com/lancaster-university/codal-microbit-v2/tree/8d17105316628b0d69f0d0b123d13c5f13f7743a/inc/bluetooth

**Comment by MrYsLab** [comment]
Thanks!

**Comment by carlosperate** [comment]
Btw, just tried a new `vagrant up` to build the V1 DAL C++ samples and it worked as expected with Yotta installed.

**Comment by MrYsLab** [comment]
I tried it again, not updating Ubuntu. It does indeed work.

Since I will use the docker version, this is no longer an issue for me, so that I will close this.

Thanks for looking into it.
